### ISSUE TITLE
Fails to Install

### ISSUE THREAD

**Issue by jsilve24** [vsbuffalo/stanhl#3]
devtools::install_github('vsbuffalo/stanhl')
Downloading GitHub repo vsbuffalo/stanhl@master
from URL https://api.github.com/repos/vsbuffalo/stanhl/zipball/master
Installing stanhl
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/x1/9_lpy_fs0kvg0p88td6_df200000gq/T/RtmplWSW1J/devtools10c6a19b3688/vsbuffalo-stanhl-b11dd19'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests 

* installing *source* package ‘stanhl’ ...
** R
** inst
** preparing package for lazy loading
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pygments.styles
Warning: running command 'python -c 'from pygments.styles import get_all_styles;print list(get_all_styles())'' had status 1
Error in opts$validators[[name]](dots[[name]]) : 
  'default' is not an available Pygments style.
Error : unable to load R code in package ‘stanhl’
ERROR: lazy loading failed for package ‘stanhl’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/stanhl’
Error: Command failed (1)

Thank you!
Justin

**Comment by XiangyunHuang** [comment]
The same errors bite me , too

details of my installation process

```r
devtools::install_github('vsbuffalo/stanhl')
Downloading GitHub repo vsbuffalo/stanhl@master
from URL https://api.github.com/repos/vsbuffalo/stanhl/zipball/master
Installing stanhl
"C:/PROGRA~1/R/R-35~1.0/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/xy-huang/AppData/Local/Temp/RtmpI79yPr/devtools1c906caf13de/vsbuffalo-stanhl-b11dd19"  \
  --library="D:/site-library" --install-tests 

* installing *source* package 'stanhl' ...
** R
** inst
** byte-compile and prepare package for lazy loading
  File "<string>", line 1
    'from
        ^
SyntaxError: EOL while scanning string literal
Warning in system(cmd, input = input, intern = TRUE) :
  running command 'python -c 'from pygments.styles import get_all_styles;print list(get_all_styles())'' had status 1
Error in opts$validators[[name]](dots[[name]]) : 
  'default' is not an available Pygments style.
Error : unable to load R code in package 'stanhl'
ERROR: lazy loading failed for package 'stanhl'
* removing 'D:/site-library/stanhl'
In R CMD INSTALL
Installation failed: Command failed (1)
```

```r
system("python --version")
Python 3.6.4 :: Anaconda, Inc.

sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.5.0  R6_2.2.2        tools_3.5.0    
 [5] withr_2.1.2     curl_3.2        memoise_1.1.0   git2r_0.21.0   
 [9] digest_0.6.15   devtools_1.13.5
```

```
(base) C:\Users\xy-huang>pygmentize -V
Pygments version 2.2.0, (c) 2006-2017 by Georg Brandl.
```

**Comment by jwalton3141** [comment]
Can you install the package from this fork: https://github.com/jr-packages/stanhl/ ? or does the issue persist?

**Comment by XiangyunHuang** [comment]
Now, It's fixed on my mac

Install Pygments with Python 3  firstly

```bash
pip install Pygments
```

Then

## Install

```
remotes::install_github('jr-packages/stanhl')
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo jr-packages/stanhl@HEAD
   checking for file ‘/private/var/folders/j6/2zkth0qd5554mr82508xgj1c0000gn/T/Rtmp5XTB4s/remotese8ee2425b1bf/jr-packa✔  checking for file ‘/private/var/folders/j6/2zkth0qd5554mr82508xgj1c0000gn/T/Rtmp5XTB4s/remotese8ee2425b1bf/jr-packages-stanhl-250b217/DESCRIPTION’
─  preparing ‘stanhl’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘stanhl_0.1.0.tar.gz’
   
* installing *source* package ‘stanhl’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (stanhl)
```

## Session Info

```
sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] zh_CN.UTF-8/zh_CN.UTF-8/zh_CN.UTF-8/C/zh_CN.UTF-8/zh_CN.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
 [1] ps_1.4.0          fansi_0.4.1       prettyunits_1.1.1
 [4] withr_2.3.0       crayon_1.3.4      rprojroot_1.3-2  
 [7] assertthat_0.2.1  R6_2.4.1          backports_1.1.10 
[10] cli_2.1.0         curl_4.3          remotes_2.2.0    
[13] callr_3.5.1       tools_4.0.2       glue_1.4.2       
[16] compiler_4.0.2    processx_3.4.4    pkgbuild_1.1.0   
```
